export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PROUDCT = "DELETE_PROUDCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT"
